
WARNING 2022-06-28 01:16:07,767 - Forbidden (Referer checking failed - https://51.250.106.80:443 does not match any trusted origins.): /mifs/.;/services/LogService
ERROR 2022-06-28 02:14:54,422 - Internal Server Error: /provider/providerproduct/131/change/
Traceback (most recent call last):
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1660, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1586, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/apple/code/project1/tune/provider/admin.py", line 15, in save_model
    super().save_model(request, obj, form, change)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1099, in save_model
    obj.save()
  File "/home/apple/code/project1/tune/provider/models.py", line 214, in save
    [f'üîë‚úÖ –î–æ–ø—É—Å—Ç–∏—Ç—å –ø–æ—Å—Ç –∫ –ø—É–±–ª–∏–∫–∞—Ü–∏–∏ id={res.id}'],
UnboundLocalError: local variable 'res' referenced before assignment
ERROR 2022-06-28 03:10:18,677 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509618211, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe3129bc070>, 'from_user': <telebot.types.User object at 0x7fe3129bc430>, 'date': 1656385818, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe3129bc880>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe3129bc340>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 03:10:18,771 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509618211, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe3129bc070>, 'from_user': <telebot.types.User object at 0x7fe3129bc430>, 'date': 1656385818, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe3129bc880>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe3129bc340>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
WARNING 2022-06-28 03:41:30,576 - Forbidden (Referer checking failed - no Referer.): /
WARNING 2022-06-28 03:41:34,398 - Forbidden (Referer checking failed - no Referer.): /
WARNING 2022-06-28 04:03:46,529 - Forbidden (Referer checking failed - Referer is insecure while host is secure.): /login
WARNING 2022-06-28 04:03:46,626 - Forbidden (Referer checking failed - Referer is insecure while host is secure.): /login
WARNING 2022-06-28 04:03:46,788 - Forbidden (Referer checking failed - Referer is insecure while host is secure.): /login
WARNING 2022-06-28 04:03:46,886 - Forbidden (Referer checking failed - Referer is insecure while host is secure.): /login
WARNING 2022-06-28 04:03:46,986 - Forbidden (Referer checking failed - Referer is insecure while host is secure.): /login
ERROR 2022-06-28 04:37:06,953 - Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
WARNING 2022-06-28 04:37:07,205 - Bad Request: /
WARNING 2022-06-28 04:44:47,748 - Forbidden (Referer checking failed - no Referer.): /HNAP1/
ERROR 2022-06-28 06:01:09,639 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509618534, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312a31460>, 'from_user': <telebot.types.User object at 0x7fe311e0da00>, 'date': 1656396069, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe312301a00>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe3121dd730>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 06:01:09,736 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509618534, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312a31460>, 'from_user': <telebot.types.User object at 0x7fe311e0da00>, 'date': 1656396069, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe312301a00>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe3121dd730>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 06:01:53,515 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509618543, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312222700>, 'from_user': <telebot.types.User object at 0x7fe3122222e0>, 'date': 1656396113, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe312222760>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe312214490>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 06:01:53,601 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509618543, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312222700>, 'from_user': <telebot.types.User object at 0x7fe3122222e0>, 'date': 1656396113, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe312222760>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe312214490>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 06:16:04,723 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509618553, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe3125ff2b0>, 'from_user': <telebot.types.User object at 0x7fe3125ff700>, 'date': 1656396964, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe3129a9970>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe3129a9880>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 06:16:04,798 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509618553, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe3125ff2b0>, 'from_user': <telebot.types.User object at 0x7fe3125ff700>, 'date': 1656396964, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe3129a9970>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe3129a9880>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 06:17:05,719 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509618563, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe31276d0a0>, 'from_user': <telebot.types.User object at 0x7fe31276dca0>, 'date': 1656397025, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe31276de80>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe31276d5e0>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 06:17:05,781 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509618563, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe31276d0a0>, 'from_user': <telebot.types.User object at 0x7fe31276dca0>, 'date': 1656397025, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe31276de80>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe31276d5e0>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 06:53:02,490 - Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
WARNING 2022-06-28 06:53:02,985 - Bad Request: /boaform/admin/formLogin
WARNING 2022-06-28 07:07:58,249 - Forbidden (Referer checking failed - no Referer.): /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
ERROR 2022-06-28 07:09:58,463 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509618741, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312104250>, 'from_user': <telebot.types.User object at 0x7fe31271b700>, 'date': 1656400198, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe31271b6d0>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe31271b400>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 07:09:58,528 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509618741, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312104250>, 'from_user': <telebot.types.User object at 0x7fe31271b700>, 'date': 1656400198, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe31271b6d0>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe31271b400>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 07:16:34,140 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509618766, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312222bb0>, 'from_user': <telebot.types.User object at 0x7fe312a6eb50>, 'date': 1656400594, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe3129bf550>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe31299b460>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 07:16:34,224 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509618766, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312222bb0>, 'from_user': <telebot.types.User object at 0x7fe312a6eb50>, 'date': 1656400594, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe3129bf550>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe31299b460>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 07:37:45,778 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509618882, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe3125f6280>, 'from_user': <telebot.types.User object at 0x7fe3125f6130>, 'date': 1656401865, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe3125f6ac0>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe3125f6370>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 07:37:45,851 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509618882, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe3125f6280>, 'from_user': <telebot.types.User object at 0x7fe3125f6130>, 'date': 1656401865, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe3125f6ac0>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe3125f6370>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 08:15:28,508 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509619014, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312240d00>, 'from_user': <telebot.types.User object at 0x7fe312240160>, 'date': 1656404128, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe31277a700>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe31277a0d0>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 08:15:28,599 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509619014, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312240d00>, 'from_user': <telebot.types.User object at 0x7fe312240160>, 'date': 1656404128, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe31277a700>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe31277a0d0>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
WARNING 2022-06-28 08:17:42,893 - Forbidden (Referer checking failed - no Referer.): /HNAP1/
ERROR 2022-06-28 08:19:29,373 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509619033, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312222cd0>, 'from_user': <telebot.types.User object at 0x7fe3122224f0>, 'date': 1656404369, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe31269d730>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe3122143a0>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 08:19:29,455 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509619033, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312222cd0>, 'from_user': <telebot.types.User object at 0x7fe3122224f0>, 'date': 1656404369, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe31269d730>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe3122143a0>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 08:21:14,469 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509619042, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe31277b610>, 'from_user': <telebot.types.User object at 0x7fe31277b190>, 'date': 1656404474, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe31277b5b0>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe31277beb0>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 08:21:14,551 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509619042, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe31277b610>, 'from_user': <telebot.types.User object at 0x7fe31277b190>, 'date': 1656404474, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe31277b5b0>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe31277beb0>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
WARNING 2022-06-28 08:37:22,985 - Forbidden (Referer checking failed - Referer is insecure while host is secure.): /boaform/admin/formLogin
ERROR 2022-06-28 09:18:04,400 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (reg_user), {'update_id': 509619457, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312703730>, 'from_user': <telebot.types.User object at 0x7fe312703460>, 'date': 1656407884, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe3126e2970>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe311e03a90>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 09:18:04,473 - –í–Ω–µ—à–Ω–∏–π –ø—Ä–∏–µ–º update (stat_user), {'update_id': 509619457, 'message': None, 'edited_message': None, 'channel_post': None, 'edited_channel_post': None, 'inline_query': None, 'chosen_inline_result': None, 'callback_query': None, 'shipping_query': None, 'pre_checkout_query': None, 'poll': None, 'poll_answer': None, 'my_chat_member': {'chat': <telebot.types.Chat object at 0x7fe312703730>, 'from_user': <telebot.types.User object at 0x7fe312703460>, 'date': 1656407884, 'old_chat_member': <telebot.types.ChatMember object at 0x7fe3126e2970>, 'new_chat_member': <telebot.types.ChatMember object at 0x7fe311e03a90>, 'invite_link': None}, 'chat_member': None, 'chat_join_request': None}
ERROR 2022-06-28 09:30:58,745 - –û—à–∏–±–∫–∞ show_model
ERROR 2022-06-28 09:30:58,960 - Internal Server Error: /api/v1
Traceback (most recent call last):
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 533, in show_model
    current_price = get_max_min_price(detail_product[0].price)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 2008, in bot
    client.process_new_updates([update])
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 490, in process_new_updates
    self.process_new_messages(new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 522, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 3449, in _notify_command_handlers
    self._exec_task(message_handler['function'], message, pass_bot=message_handler['pass_bot'], task_type='handler')
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 784, in _exec_task
    task(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 615, in show_model
    text='–û—à–∏–±–∫–∞ show_model'
TypeError: can only concatenate str (not "int") to str
ERROR 2022-06-28 09:30:59,283 - –û—à–∏–±–∫–∞ show_model
ERROR 2022-06-28 09:30:59,318 - Internal Server Error: /api/v1
Traceback (most recent call last):
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 533, in show_model
    current_price = get_max_min_price(detail_product[0].price)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 2008, in bot
    client.process_new_updates([update])
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 490, in process_new_updates
    self.process_new_messages(new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 522, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 3449, in _notify_command_handlers
    self._exec_task(message_handler['function'], message, pass_bot=message_handler['pass_bot'], task_type='handler')
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 784, in _exec_task
    task(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 615, in show_model
    text='–û—à–∏–±–∫–∞ show_model'
TypeError: can only concatenate str (not "int") to str
ERROR 2022-06-28 09:31:01,641 - –û—à–∏–±–∫–∞ show_model
ERROR 2022-06-28 09:31:01,691 - Internal Server Error: /api/v1
Traceback (most recent call last):
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 533, in show_model
    current_price = get_max_min_price(detail_product[0].price)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 2008, in bot
    client.process_new_updates([update])
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 490, in process_new_updates
    self.process_new_messages(new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 522, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 3449, in _notify_command_handlers
    self._exec_task(message_handler['function'], message, pass_bot=message_handler['pass_bot'], task_type='handler')
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 784, in _exec_task
    task(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 615, in show_model
    text='–û—à–∏–±–∫–∞ show_model'
TypeError: can only concatenate str (not "int") to str
ERROR 2022-06-28 09:31:06,017 - –û—à–∏–±–∫–∞ show_model
ERROR 2022-06-28 09:31:06,049 - Internal Server Error: /api/v1
Traceback (most recent call last):
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 533, in show_model
    current_price = get_max_min_price(detail_product[0].price)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 2008, in bot
    client.process_new_updates([update])
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 490, in process_new_updates
    self.process_new_messages(new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 522, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 3449, in _notify_command_handlers
    self._exec_task(message_handler['function'], message, pass_bot=message_handler['pass_bot'], task_type='handler')
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 784, in _exec_task
    task(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 615, in show_model
    text='–û—à–∏–±–∫–∞ show_model'
TypeError: can only concatenate str (not "int") to str
ERROR 2022-06-28 09:31:14,385 - –û—à–∏–±–∫–∞ show_model
ERROR 2022-06-28 09:31:14,421 - Internal Server Error: /api/v1
Traceback (most recent call last):
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 533, in show_model
    current_price = get_max_min_price(detail_product[0].price)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 2008, in bot
    client.process_new_updates([update])
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 490, in process_new_updates
    self.process_new_messages(new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 522, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 3449, in _notify_command_handlers
    self._exec_task(message_handler['function'], message, pass_bot=message_handler['pass_bot'], task_type='handler')
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 784, in _exec_task
    task(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 615, in show_model
    text='–û—à–∏–±–∫–∞ show_model'
TypeError: can only concatenate str (not "int") to str
ERROR 2022-06-28 09:31:30,761 - –û—à–∏–±–∫–∞ show_model
ERROR 2022-06-28 09:31:30,795 - Internal Server Error: /api/v1
Traceback (most recent call last):
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 533, in show_model
    current_price = get_max_min_price(detail_product[0].price)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 2008, in bot
    client.process_new_updates([update])
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 490, in process_new_updates
    self.process_new_messages(new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 522, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 3449, in _notify_command_handlers
    self._exec_task(message_handler['function'], message, pass_bot=message_handler['pass_bot'], task_type='handler')
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 784, in _exec_task
    task(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 615, in show_model
    text='–û—à–∏–±–∫–∞ show_model'
TypeError: can only concatenate str (not "int") to str
ERROR 2022-06-28 09:32:03,127 - –û—à–∏–±–∫–∞ show_model
ERROR 2022-06-28 09:32:03,160 - Internal Server Error: /api/v1
Traceback (most recent call last):
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 533, in show_model
    current_price = get_max_min_price(detail_product[0].price)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 2008, in bot
    client.process_new_updates([update])
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 490, in process_new_updates
    self.process_new_messages(new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 522, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 3449, in _notify_command_handlers
    self._exec_task(message_handler['function'], message, pass_bot=message_handler['pass_bot'], task_type='handler')
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 784, in _exec_task
    task(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 615, in show_model
    text='–û—à–∏–±–∫–∞ show_model'
TypeError: can only concatenate str (not "int") to str
ERROR 2022-06-28 09:33:03,470 - –û—à–∏–±–∫–∞ show_model
ERROR 2022-06-28 09:33:03,501 - Internal Server Error: /api/v1
Traceback (most recent call last):
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 533, in show_model
    current_price = get_max_min_price(detail_product[0].price)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 2008, in bot
    client.process_new_updates([update])
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 490, in process_new_updates
    self.process_new_messages(new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 522, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 3449, in _notify_command_handlers
    self._exec_task(message_handler['function'], message, pass_bot=message_handler['pass_bot'], task_type='handler')
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 784, in _exec_task
    task(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 615, in show_model
    text='–û—à–∏–±–∫–∞ show_model'
TypeError: can only concatenate str (not "int") to str
ERROR 2022-06-28 09:34:03,807 - –û—à–∏–±–∫–∞ show_model
ERROR 2022-06-28 09:34:03,839 - Internal Server Error: /api/v1
Traceback (most recent call last):
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 533, in show_model
    current_price = get_max_min_price(detail_product[0].price)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 2008, in bot
    client.process_new_updates([update])
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 490, in process_new_updates
    self.process_new_messages(new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 522, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 3449, in _notify_command_handlers
    self._exec_task(message_handler['function'], message, pass_bot=message_handler['pass_bot'], task_type='handler')
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 784, in _exec_task
    task(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 615, in show_model
    text='–û—à–∏–±–∫–∞ show_model'
TypeError: can only concatenate str (not "int") to str
ERROR 2022-06-28 09:35:04,139 - –û—à–∏–±–∫–∞ show_model
ERROR 2022-06-28 09:35:04,171 - Internal Server Error: /api/v1
Traceback (most recent call last):
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 533, in show_model
    current_price = get_max_min_price(detail_product[0].price)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 2008, in bot
    client.process_new_updates([update])
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 490, in process_new_updates
    self.process_new_messages(new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 522, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 3449, in _notify_command_handlers
    self._exec_task(message_handler['function'], message, pass_bot=message_handler['pass_bot'], task_type='handler')
  File "/home/apple/code/project1/env/lib/python3.8/site-packages/telebot/__init__.py", line 784, in _exec_task
    task(*args, **kwargs)
  File "/home/apple/code/project1/tune/tune_admin/views.py", line 615, in show_model
    text='–û—à–∏–±–∫–∞ show_model'
TypeError: can only concatenate str (not "int") to str
